{
  config,
  lib,
  ...
}:
with lib; {
  options.fht.theme.targets.awesomewm = {
    enable = mkBoolOpt' false "Whether to enable the AwesomeWM theme.";
  };

  # Custom layout icons.

  config = let
    cfg = config.fht.theme.targets.awesomewm;
    theme = config.fht.theme;
  in
    lib.mkIf cfg.enable {
      home.xdg.configFile."theme/awesome/palette.lua".text = with theme.colors.withHashtag; ''
        -- HEY, don't edit this! It was autogenerated by nix.
        -- Current theme: ${theme.name}
        return {
            black        = "${black}",
            darker_black = "${darker_black}",
            black2       = "${black2}",
            onebg        = "${onebg}",
            oneb2        = "${oneb2}",
            oneb3        = "${oneb3}",
            statusline   = "${statusline}",
            white        = "${white}",
            grey         = "${grey}",
            grey_fg      = "${grey_fg}",
            grey_fg2     = "${grey_fg2}",
            light_grey   = "${light_grey}",
            red          = "${red}",
            green        = "${green}",
            yellow       = "${yellow}",
            blue         = "${blue}",
            magenta      = "${magenta}",
            cyan         = "${cyan}",
        }
      '';

      # Not working for now..
      # fht.theme.onReload.awesomewm = "awesome-client 'awesome.restart()'";
    };
}
