#!/usr/bin/env zsh

# ~/.config/zsh/.zshrc -*- Configuration file for zsh.

# Setup for interactives sessions.
if [[ $TERM != dumb ]]; then
    # General zsh configuration.
    source $ZDOTDIR/options.zsh
    source $ZDOTDIR/compinit.zsh # gotta source this before
    source $ZDOTDIR/alias.zsh

    # Source extra configuration generated by nixos.
    # This is for modules that require additional initialisation at the shell
    # level.
    _source $XDG_CONFIG_HOME/shell/extraInit.sh
fi
