#!/usr/bin/env zsh

# ~/.config/zsh/alias.zsh -*- Custom aliases.

# Just gotta save typing three letters out of one program.
alias da="doas --" \
    pm="pulsemixer" \
    nmt="nmtui-connect" \
    bt="bluetoothctl" \
    vim="nvim" \
    v="nvim" \
    tb="nc termbin.com 9999";

# Default options for some programs
alias less="less --use-color --color=Pbk --color=NK- --force --ignore-case --incsearch -N" \
    grep="grep --extended-regexp --ignore-case --with-filename --color=auto" \
    ip="ip -h -s --color=always" \
    diff="diff --color=auto"

# Safer move, copy, and delete operations
alias mv="mv -fv --" cp="cp -LfRv --" rm="rm -Idrv --";

# Make directory but it's idempotent.
alias mkdir="mkdir -pv";
# A better mkdirectory.
function md { mkdir -pv "${1}" && cd "${1}" || return; }; compdef md=mkdir

# An rsync that respects gitignore
# Stolen from Henrik Lissner's dotfiles.
rcp() {
  # -a = -rlptgoD
  #   -r = recursive
  #   -l = copy symlinks as symlinks
  #   -p = preserve permissions
  #   -t = preserve mtimes
  #   -g = preserve owning group
  #   -o = preserve owner
  # -z = use compression
  # -P = show progress on transferred file
  # -J = don't touch mtimes on symlinks (always errors)
  rsync -azPJ --include=.git --filter=':- .gitignore'  \
    --filter=":- $XDG_CONFIG_HOME/git/ignore" "$@"
}; compdef rcp=rsync
# Some additional variants of this command.
alias rcpd='rcp --delete --delete-after' \
    rcpu='rcp --chmod=go=' \
    rcpdu='rcpd --chmod=go='

# Easier to copy/paste stuff from the terminal.
alias yank='xclip -selection clipboard -in' \
    paste='xclip -selection clipboard -out'

# Systemctl stuff.
alias jc='journalctl -xe' \
    sc=systemctl dsc='doas systemctl'

# Create a reminder with human-readable durations, e.g. 15m, 1h, 40s, etc
function r {
  local time=$1; shift
  local urgency=${2:-normal}; shift
  sched "$time" "notify-send --urgency=critical '${urgency}' '$@'; ding";
}; compdef r=sched

# Extra aliases file generated by NixOS.
_source $XDG_CONFIG_HOME/shell/aliases.sh
